#!/bin/sh /etc/rc.common

START=25
STOP=75

USE_PROCD=1
PROG=/usr/bin/rsu-connector
CONFIG_FILE=/etc/rsu-connector/rsu-connector-config.json

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" "$CONFIG_FILE"
	procd_set_param respawn 5 1 -1
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
